spring.datasource.url=jdbc:mysql://${mysql.railway.internal}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=root
spring.datasource.password=fnqDtnvwGqdHOjdBXBkKlqfkVyqJnwDK

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}